### PR TITLE
New Chapter Collections

### PR DESCRIPTION
**Pull request by deeper-x**
Following PR #67 .
 
- I created a New Chapter 05_Collections.
- I added new content:
1. List
2. Set
3. Map

- I moved into 05_Collections folder, collections-related part of stdlib chapter (everything except let and with).

Updated chapters result:
```bash
$ tree examples/05_Collections/ examples/06_stdlib/
examples/05_Collections/
├── 00_description.md
├── 01_List.md
├── 02_Set.md
├── 03_Map.md
├── 04_filter.md
├── 04_map.md
├── 05_existential.md
├── 06_find.md
├── 07_firstlast.md
├── 08_count.md
├── 10_associateBy.md
├── 11_partition.md
├── 12_flatMap.md
├── 13_max.md
├── 14_sorted.md
├── 15_Map_getValue.md
├── 16_zip.md
└── 17_getOrElse.md
examples/06_stdlib/
├── 00_description.md
├── 01_letFunction.md
└── 02_withFunction.md

```

- Furthermore, I took the liberty of renaming chapters after 05_Collections, just incrementing values:
```bash
$ ls -1 examples/
01_introduction
02_control_flow
03_special_classes
04_functional
05_Collections
06_stdlib
07_Delegation
08_productivity_boosters
09_Kotlin_JS
``` 
- I updated descriptions, following "Wording, style and formatting" rules.

Please let me know if this PR meets your requirements.

Thank you

Alberto

Note:
I created a brand new PR because I prefer to send "clean" request (in the previous one I didn't like what happened locally with .idea/* and .gitattributes stuff). Now I'm working locally with my own .gitignore and everything is working by default.

### CODE REVIEW

**Comment by p7nov** [comment]
Hi again!
Thanks, I'll be able to test it on Monday.

**Comment by p7nov** [comment]
Everything looks fine now. @AlexanderPrendota I think we can merge.

**Comment by p7nov** [comment]
Alberto, thanks again for your contribution!

Regards, Pavel

**Comment by deeper-x** [comment]
It's a pleasure to collaborate in projects like this. See you next time! :)

**Pull request merged**
